[build-system]
requires = ["uv_build>=0.10.9,<0.11.0"]
build-backend = "uv_build"

[project]
name = "korp-backend"
version = "9.0.0.dev0"
description = "Backend for Korp, Språkbanken's corpus search tool"
readme = "README.md"
requires-python = ">=3.11"
license = "MIT"
license-files = ["LICENSE"]
authors = [
    { name = "Språkbanken Text", email = "sb-info@svenska.gu.se" }
]
dependencies = [
    "fastapi==0.135.1",
    "sqlalchemy~=2.0",
    "asyncmy~=0.2.11",  # MySQL driver for SQLAlchemy
    "psutil~=7.2",
    "aiomcache~=0.8.2",  # Memcached client
    "python-dateutil~=2.9",
    "PyYAML~=6.0",
    "pydantic-settings~=2.13"  # For configuration management
]

[project.optional-dependencies]
rate-limiting = [
    "limits[async-memcached]~=5.8"
]
server = [
    "gunicorn>=25.1",
    "uvloop"  # Used by Gunicorn's ASGI worker for improved performance
]
jwt = [
    "pyjwt[crypto]"  # For JWT support in authentication plugin
]

[dependency-groups]
dev = [
    "fastapi-cli[standard-no-fastapi-cloud-cli]",
    "ruff~=0.15.0",
    {include-group = "test"}
]
test = [
    "httpx~=0.28.0",  # For the test client
    "pytest~=9.0",
    "PyMySQL~=1.1",  # Sync MySQL driver used by test DB utilities
    "pytest-sugar",
]

[project.urls]
Homepage = "https://github.com/spraakbanken/korp-backend/"

[tool.uv]
required-version = ">=0.10"

[tool.uv.build-backend]
module-name = "korp"
module-root = ""

[tool.ruff]
line-length = 120
output-format = "grouped"

[tool.ruff.lint]
select = [
    "A",      # flake8-builtins
    "ANN",    # flake8-annotations
    "ARG",    # flake8-unused-arguments
    "B",      # flake8-bugbear
    "C4",     # flake8-comprehensions
    "COM",    # flake8-commas
    "D",      # pydocstyle
    "DOC",    # pydoclint
    "E",      # pycodestyle: errors
    "F",      # Pyflakes
    "FA",     # flake-8-future-annotations
    "FLY",    # flynt
    "FURB",   # refurb
    "G",      # flake8-logging-format
    "I",      # isort
    "ISC",    # flake8-implicit-str-concat
    "N",      # pep8-naming
    "PERF",   # Perflint
    "PIE",    # flake8-pie
    "PL",     # Pylint
    "PT",     # flake8-pytest-style
    "PTH",    # flake8-use-pathlib
    "Q",      # flake8-quotes
    "RET",    # flake8-return
    "RSE",    # flake8-raise
    "RUF",    # Ruff-specific rules
    "S113",   # flake8-bandit: request-without-timeout
    "SIM",    # flake8-simplify
    "T20",    # flake8-print
    "TID",    # flake8-tidy-imports
    "UP",     # pyupgrade
    "W",      # pycodestyle: warnings
]
ignore = [
    "ANN401",  # flake8-annotations: any-type
    "COM812",  # flake8-commas: missing-trailing-comma
    "E741",    # pycodestyle: ambiguous-variable-name
    "PERF203", # Perflint: try-except-in-loop
    "PLR09",   # Pylint: too-many-*
    "PLR1702", # Pylint: too-many-nested-blocks
    "SIM105",  # flake8-simplify: suppressible-exception
]
preview = true

[tool.ruff.lint.pydocstyle]
convention = "google"
